# Generated by Django 4.2.5 on 2023-10-01 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('created_at', models.TimeField(auto_now=True)),
                ('updated_at', models.TimeField(auto_now_add=True)),
            ],
        ),
    ]
